.catalog:
  name: "Kibana"
  version: "4.1.1-rancher1"
  description: "Kibana: Explore & Visualize Your Data"
  uuid: kibana-0
  questions:
    - variable: "ELASTICSEARCH_URL"
      description: "Link to your elasticsearch instance"
      label: "Elasticsearch source"
      type: "string"
      required: true
      default: "http://elasticsearch:9200"
nginx-proxy:
  metadata:
    nginx:
      conf:
        servername: "kibana"
        upstream_port: 5601 
